hyperskill_project:
  id: 305
  ide_files: https://cogniterra.org/media/attachments/lesson/27178/additional_files.json
  is_template_based: false
  use_ide: true
  environment: unittest
update_date: "Tue, 11 Jun 2024 04:41:21 UTC"
stages:
  - id: 1712
    step: 24118
    is_completed: true
  - id: 1713
    step: 24119
    is_completed: true
  - id: 1714
    step: 24120
    is_completed: true
  - id: 1715
    step: 24121
    is_completed: true
topics:
  0:
    - title: Computer algorithms
      theory_id: 16547
    - title: Operating systems
      theory_id: 9704
    - title: Command line overview
      theory_id: 8977
    - title: Working with file modes and permissions
      theory_id: 13961
    - title: Introduction to Python
      theory_id: 5204
    - title: Writing first program
      theory_id: 5208
    - title: "PEP 8: Coding style guide"
      theory_id: 5879
    - title: Taking user's input
      theory_id: 5913
    - title: If statement
      theory_id: 5953
    - title: Else statement
      theory_id: 5932
    - title: For loop
      theory_id: 6065
    - title: Comments
      theory_id: 6081
    - title: Importing modules
      theory_id: 6019
    - title: Installing packages with pip
      theory_id: 6230
    - title: Virtual Environment
      theory_id: 13923
    - title: PyCharm basics
      theory_id: 6193
    - title: What are bugs
      theory_id: 5504
    - title: Class
      theory_id: 6661
    - title: Class instances
      theory_id: 6669
    - title: Running Python applications in PyCharm
      theory_id: 19153
    - title: Files
      theory_id: 13025
    - title: Introduction to Linux
      theory_id: 9526
    - title: File types
      theory_id: 13017
    - title: Random module
      theory_id: 6263
    - title: File modes and permissions
      theory_id: 13953
    - title: Files in Python
      theory_id: 8691
    - title: "Real-time interpreter: Shell"
      theory_id: 8133
    - title: Experiments with Python shell
      theory_id: 8238
    - title: Basic data types
      theory_id: 5852
    - title: Variables
      theory_id: 5859
    - title: Invoking functions
      theory_id: 5891
    - title: Boolean type and operations. True and false
      theory_id: 6025
    - title: Comparisons
      theory_id: 5920
    - title: List
      theory_id: 5979
    - title: Indexes
      theory_id: 6189
    - title: Declaring functions
      theory_id: 5900
    - title: "Working with strings: basic methods"
      theory_id: 6842
    - title: List comprehension
      theory_id: 6315
    - title: Nested lists
      theory_id: 6938
    - title: Type casting
      theory_id: 6224
    - title: Sep and end arguments of print
      theory_id: 7452
  1:
    - title: "Big O: how to count it"
      theory_id: 35901
    - title: Complexity cases and how to use them
      theory_id: 20084
    - title: Abstract and concrete data structures
      theory_id: 16927
    - title: Pseudocode
      theory_id: 15090
    - title: Pseudocode basics
      theory_id: 19510
    - title: Fixed-size array
      theory_id: 20078
    - title: Dynamic array
      theory_id: 5357
    - title: Complex constructions in pseudocode
      theory_id: 20922
    - title: Greedy algorithms
      theory_id: 23311
    - title: Multi-line programs
      theory_id: 5233
    - title: Elif statement
      theory_id: 5926
    - title: Debugging Python applications in PyCharm
      theory_id: 19163
    - title: Inheritance
      theory_id: 9844
    - title: Inheritance in Python
      theory_id: 7235
    - title: Polymorphism
      theory_id: 10027
    - title: Method overriding
      theory_id: 7629
    - title: Program execution
      theory_id: 6047
    - title: Errors
      theory_id: 6052
    - title: Exceptions
      theory_id: 6042
    - title: Built-in exceptions
      theory_id: 11680
    - title: Exception handling
      theory_id: 6270
    - title: User-defined exceptions
      theory_id: 10217
    - title: Graph
      theory_id: 15967
    - title: "Nodes, cycles and paths"
      theory_id: 15968
    - title: Representation of graphs
      theory_id: 15969
    - title: Weighted graph
      theory_id: 5645
    - title: Sorting problem
      theory_id: 4954
    - title: Recursion basics
      theory_id: 5984
    - title: Tree
      theory_id: 5121
    - title: Spanning tree
      theory_id: 5652
  2:
    - title: Reading files
      theory_id: 8139
    - title: Writing files
      theory_id: 8334
    - title: Context manager
      theory_id: 8702
    - title: Pickle
      theory_id: 12651
    - title: Debugging in shell
      theory_id: 8244
  3:
    - title: Stack
      theory_id: 5252
    - title: Decrease and conquer
      theory_id: 14669
    - title: Algorithms in Python
      theory_id: 7316
    - title: Stack in Python
      theory_id: 8915
    - title: Graph traversal
      theory_id: 31965
    - title: Depth-first search
      theory_id: 17546
    - title: Intro to computational thinking
      theory_id: 8742
    - title: Components of computational thinking
      theory_id: 8745
    - title: "Function, arguments and parameters"
      theory_id: 7248
    - title: Operations with list
      theory_id: 6031
    - title: Functional decomposition
      theory_id: 9571
