hyperskill_project:
  id: 307
  ide_files: https://cogniterra.org/media/attachments/lesson/27204/additional_files.json
  is_template_based: false
  use_ide: true
  environment: unittest
update_date: "Tue, 14 May 2024 21:37:05 UTC"
stages:
  - id: 1721
    step: 24271
    is_completed: true
  - id: 1722
    step: 24272
    is_completed: true
  - id: 1723
    step: 24273
    is_completed: true
  - id: 1724
    step: 24274
    is_completed: true
  - id: 1725
    step: 24275
    is_completed: true
  - id: 1726
    step: 24276
    is_completed: true
topics:
  0:
    - title: Introduction to Python
      theory_id: 5204
    - title: Writing first program
      theory_id: 5208
    - title: "PEP 8: Coding style guide"
      theory_id: 5879
    - title: Multi-line programs
      theory_id: 5233
    - title: Naming variables
      theory_id: 5885
    - title: Taking user's input
      theory_id: 5913
    - title: Program with numbers
      theory_id: 5872
    - title: If statement
      theory_id: 5953
    - title: Else statement
      theory_id: 5932
    - title: For loop
      theory_id: 6065
    - title: Comments
      theory_id: 6081
    - title: Importing modules
      theory_id: 6019
    - title: Installing packages with pip
      theory_id: 6230
    - title: Virtual Environment
      theory_id: 13923
    - title: PyCharm basics
      theory_id: 6193
    - title: Elif statement
      theory_id: 5926
    - title: While loop
      theory_id: 5940
    - title: "Loop control: break, continue, pass"
      theory_id: 6302
    - title: Class
      theory_id: 6661
    - title: Class instances
      theory_id: 6669
    - title: Running Python applications in PyCharm
      theory_id: 19153
    - title: Debugging Python applications in PyCharm
      theory_id: 19163
    - title: Inheritance
      theory_id: 9844
    - title: Inheritance in Python
      theory_id: 7235
    - title: Polymorphism
      theory_id: 10027
    - title: Method overriding
      theory_id: 7629
    - title: Program execution
      theory_id: 6047
    - title: Errors
      theory_id: 6052
    - title: Exceptions
      theory_id: 6042
    - title: Built-in exceptions
      theory_id: 11680
    - title: Exception handling
      theory_id: 6270
    - title: Math functions
      theory_id: 6256
    - title: Float special values
      theory_id: 8804
    - title: Basic data types
      theory_id: 5852
    - title: Variables
      theory_id: 5859
    - title: Integer arithmetic
      theory_id: 5865
    - title: Invoking functions
      theory_id: 5891
    - title: Boolean type and operations. True and false
      theory_id: 6025
    - title: Comparisons
      theory_id: 5920
    - title: List
      theory_id: 5979
    - title: Indexes
      theory_id: 6189
    - title: Declaring functions
      theory_id: 5900
    - title: Identity testing
      theory_id: 8077
    - title: Quotes and multi-line strings
      theory_id: 5814
    - title: "Working with strings: basic methods"
      theory_id: 6842
    - title: Escape sequences
      theory_id: 7130
    - title: Splitting strings and joining lists
      theory_id: 6972
    - title: Type casting
      theory_id: 6224
  1:
    - title: Command line arguments
      theory_id: 7981
    - title: Argparse module
      theory_id: 11389
  2:
    - title: Computer algorithms
      theory_id: 16547
    - title: "Big O: how to count it"
      theory_id: 35901
    - title: Complexity cases and how to use them
      theory_id: 20084
    - title: Abstract and concrete data structures
      theory_id: 16927
    - title: Pseudocode
      theory_id: 15090
    - title: Pseudocode basics
      theory_id: 19510
    - title: Fixed-size array
      theory_id: 20078
    - title: Dynamic array
      theory_id: 5357
    - title: Complex constructions in pseudocode
      theory_id: 20922
    - title: Divide and conquer
      theory_id: 19087
    - title: Decrease and conquer
      theory_id: 14669
    - title: Sorting problem
      theory_id: 4954
    - title: Recursion basics
      theory_id: 5984
    - title: Insertion sort
      theory_id: 19086
    - title: Merge sort
      theory_id: 29428
  3:
    - title: "Function, arguments and parameters"
      theory_id: 7248
    - title: Dictionary
      theory_id: 6481
    - title: Dictionary methods
      theory_id: 9008
  4:
    - title: User-defined exceptions
      theory_id: 10217
    - title: Assert statement
      theory_id: 10372
  5:
    - title: Operating systems
      theory_id: 9704
    - title: Command line overview
      theory_id: 8977
    - title: Working with file modes and permissions
      theory_id: 13961
    - title: Files
      theory_id: 13025
    - title: Introduction to Linux
      theory_id: 9526
    - title: File types
      theory_id: 13017
    - title: File modes and permissions
      theory_id: 13953
    - title: Files in Python
      theory_id: 8691
    - title: Reading files
      theory_id: 8139
    - title: Writing files
      theory_id: 8334
