hyperskill_project:
  id: 92
  ide_files: https://cogniterra.org/media/attachments/lesson/24624/additional_files.json
  is_template_based: false
  use_ide: true
  environment: unittest
update_date: "Thu, 01 Jan 1970 00:00:00 UTC"
stages:
  - id: 510
    step: 8282
    is_completed: true
  - id: 511
    step: 8283
    is_completed: true
  - id: 512
    step: 8284
    is_completed: true
  - id: 513
    step: 8285
    is_completed: true
  - id: 514
    step: 8286
    is_completed: true
topics:
  0:
    - title: What is math?
      theory_id: 28537
    - title: Applications of math
      theory_id: 28832
    - title: "Math notations, formulas, and statements"
      theory_id: 28757
    - title: Basic concepts
      theory_id: 26143
    - title: Cartesian coordinates
      theory_id: 13114
    - title: Computer algorithms
      theory_id: 16547
    - title: "Big O: how to count it"
      theory_id: 35901
    - title: Complexity cases and how to use them
      theory_id: 20084
    - title: Basics of sets
      theory_id: 8220
    - title: Basics of functions
      theory_id: 8857
    - title: Properties of functions
      theory_id: 20683
    - title: Abstract and concrete data structures
      theory_id: 16927
    - title: Command line overview
      theory_id: 8977
    - title: Parameters and options
      theory_id: 9746
    - title: Properties of numerical functions
      theory_id: 20704
    - title: Pseudocode
      theory_id: 15090
    - title: Pseudocode basics
      theory_id: 19510
    - title: "Vectors, matrices, scalars"
      theory_id: 16969
    - title: Introduction to matrices
      theory_id: 7112
    - title: Intro to NumPy
      theory_id: 9672
    - title: Array creation and indexing
      theory_id: 10077
    - title: Vector operations
      theory_id: 29446
    - title: Types of matrices
      theory_id: 17812
    - title: Operations with matrices
      theory_id: 7296
    - title: Vector norm and distance between vectors
      theory_id: 33339
    - title: Vector dot product
      theory_id: 29680
    - title: Matrix multiplication
      theory_id: 7372
    - title: Linear combinations and linear independence
      theory_id: 29596
    - title: Operations with several arrays
      theory_id: 10785
    - title: Operations with an array
      theory_id: 10170
    - title: Boolean operations on arrays
      theory_id: 11070
    - title: Data types in NumPy
      theory_id: 10095
    - title: Euclidean spaces
      theory_id: 30535
    - title: Projections
      theory_id: 32081
    - title: Introduction to linear operators
      theory_id: 31332
    - title: Linear subspaces
      theory_id: 30579
    - title: Null space and range
      theory_id: 32051
    - title: Eigenvalues and eigenvectors
      theory_id: 30223
    - title: Actions with linear operators
      theory_id: 31420
    - title: An inverse operator
      theory_id: 10599
    - title: Submodule linalg
      theory_id: 11207
    - title: Orthogonal and orthonormal bases
      theory_id: 34027
    - title: Complex constructions in pseudocode
      theory_id: 20922
    - title: Introduction to Python
      theory_id: 5204
    - title: Writing first program
      theory_id: 5208
    - title: "PEP 8: Coding style guide"
      theory_id: 5879
    - title: Multi-line programs
      theory_id: 5233
    - title: Naming variables
      theory_id: 5885
    - title: Taking user's input
      theory_id: 5913
    - title: Program with numbers
      theory_id: 5872
    - title: If statement
      theory_id: 5953
    - title: Else statement
      theory_id: 5932
    - title: For loop
      theory_id: 6065
    - title: Comments
      theory_id: 6081
    - title: Importing modules
      theory_id: 6019
    - title: Creating modules
      theory_id: 6057
    - title: Multiple modules. Package
      theory_id: 6384
    - title: Installing packages with pip
      theory_id: 6230
    - title: Virtual Environment
      theory_id: 13923
    - title: PyCharm basics
      theory_id: 6193
    - title: Elif statement
      theory_id: 5926
    - title: Class
      theory_id: 6661
    - title: Class instances
      theory_id: 6669
    - title: Methods
      theory_id: 6931
    - title: Methods and attributes
      theory_id: 6981
    - title: Running Python applications in PyCharm
      theory_id: 19153
    - title: Graph
      theory_id: 15967
    - title: "Nodes, cycles and paths"
      theory_id: 15968
    - title: How to read the documentation
      theory_id: 12125
    - title: Connectivity in graphs
      theory_id: 31327
    - title: Basic data types
      theory_id: 5852
    - title: Variables
      theory_id: 5859
    - title: Integer arithmetic
      theory_id: 5865
    - title: Invoking functions
      theory_id: 5891
    - title: Boolean type and operations. True and false
      theory_id: 6025
    - title: Comparisons
      theory_id: 5920
    - title: List
      theory_id: 5979
    - title: Indexes
      theory_id: 6189
    - title: Declaring functions
      theory_id: 5900
    - title: Global vs local. Scopes
      theory_id: 6322
    - title: Quotes and multi-line strings
      theory_id: 5814
    - title: String formatting
      theory_id: 6037
    - title: List comprehension
      theory_id: 6315
    - title: Dictionary
      theory_id: 6481
    - title: Slicing
      theory_id: 6177
    - title: Nested lists
      theory_id: 6938
    - title: Type casting
      theory_id: 6224
  1:
    - title: While loop
      theory_id: 5940
    - title: "Loop control: break, continue, pass"
      theory_id: 6302
  3:
    - title: Immutability
      theory_id: 7929
    - title: What is object-oriented programming
      theory_id: 3614
    - title: Identity testing
      theory_id: 8077
    - title: Objects in Python
      theory_id: 9262
    - title: "Function, arguments and parameters"
      theory_id: 7248
    - title: Operations with list
      theory_id: 6031
    - title: Default arguments
      theory_id: 10295
    - title: Tuple
      theory_id: 7462
    - title: Args
      theory_id: 8560
    - title: Dictionary methods
      theory_id: 9008
    - title: Operations with dictionary
      theory_id: 11096
    - title: Kwargs
      theory_id: 9544
    - title: Lambda functions
      theory_id: 7092
  4:
    - title: Docstrings
      theory_id: 11869
    - title: Pydoc
      theory_id: 18505
    - title: Function annotations
      theory_id: 15664
